//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuesto.PresupuestoSisWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WS_PresupuestoSis")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CentroCostosMap", Namespace="http://schemas.datacontract.org/2004/07/ModelMap")]
    [System.SerializableAttribute()]
    public partial class CentroCostosMap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdBDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdBD {
            get {
                return this.IdBDField;
            }
            set {
                if ((this.IdBDField.Equals(value) != true)) {
                    this.IdBDField = value;
                    this.RaisePropertyChanged("IdBD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProyectoCentroCostosMap", Namespace="http://schemas.datacontract.org/2004/07/ModelMap")]
    [System.SerializableAttribute()]
    public partial class ProyectoCentroCostosMap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroCostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdBDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroCosto {
            get {
                return this.CentroCostoField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroCostoField, value) != true)) {
                    this.CentroCostoField = value;
                    this.RaisePropertyChanged("CentroCosto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdBD {
            get {
                return this.IdBDField;
            }
            set {
                if ((this.IdBDField.Equals(value) != true)) {
                    this.IdBDField = value;
                    this.RaisePropertyChanged("IdBD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InflacionMap", Namespace="http://schemas.datacontract.org/2004/07/ModelMap")]
    [System.SerializableAttribute()]
    public partial class InflacionMap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AnnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdBDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerSemestreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoSemestreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Anno {
            get {
                return this.AnnoField;
            }
            set {
                if ((this.AnnoField.Equals(value) != true)) {
                    this.AnnoField = value;
                    this.RaisePropertyChanged("Anno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdBD {
            get {
                return this.IdBDField;
            }
            set {
                if ((this.IdBDField.Equals(value) != true)) {
                    this.IdBDField = value;
                    this.RaisePropertyChanged("IdBD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerSemestre {
            get {
                return this.PrimerSemestreField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerSemestreField, value) != true)) {
                    this.PrimerSemestreField = value;
                    this.RaisePropertyChanged("PrimerSemestre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoSemestre {
            get {
                return this.SegundoSemestreField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoSemestreField, value) != true)) {
                    this.SegundoSemestreField = value;
                    this.RaisePropertyChanged("SegundoSemestre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonedaMap", Namespace="http://schemas.datacontract.org/2004/07/ModelMap")]
    [System.SerializableAttribute()]
    public partial class MonedaMap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaContableMap", Namespace="http://schemas.datacontract.org/2004/07/ModelMap")]
    [System.SerializableAttribute()]
    public partial class CuentaContableMap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdBDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoCuentaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdBD {
            get {
                return this.IdBDField;
            }
            set {
                if ((this.IdBDField.Equals(value) != true)) {
                    this.IdBDField = value;
                    this.RaisePropertyChanged("IdBD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoCuenta {
            get {
                return this.TipoCuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCuentaField, value) != true)) {
                    this.TipoCuentaField = value;
                    this.RaisePropertyChanged("TipoCuenta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoCuentaContableMap", Namespace="http://schemas.datacontract.org/2004/07/ModelMap")]
    [System.SerializableAttribute()]
    public partial class TipoCuentaContableMap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoCambioMap", Namespace="http://schemas.datacontract.org/2004/07/ModelMap")]
    [System.SerializableAttribute()]
    public partial class TipoCambioMap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AñoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presupuesto.PresupuestoSisWS.MesMap[] MesesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonedaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Año {
            get {
                return this.AñoField;
            }
            set {
                if ((this.AñoField.Equals(value) != true)) {
                    this.AñoField = value;
                    this.RaisePropertyChanged("Año");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presupuesto.PresupuestoSisWS.MesMap[] Meses {
            get {
                return this.MesesField;
            }
            set {
                if ((object.ReferenceEquals(this.MesesField, value) != true)) {
                    this.MesesField = value;
                    this.RaisePropertyChanged("Meses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MesMap", Namespace="http://schemas.datacontract.org/2004/07/ModelMap")]
    [System.SerializableAttribute()]
    public partial class MesMap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mes {
            get {
                return this.MesField;
            }
            set {
                if ((object.ReferenceEquals(this.MesField, value) != true)) {
                    this.MesField = value;
                    this.RaisePropertyChanged("Mes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CargasSocialesMap", Namespace="http://schemas.datacontract.org/2004/07/ModelMap")]
    [System.SerializableAttribute()]
    public partial class CargasSocialesMap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuentaContableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PorcentajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaContable {
            get {
                return this.CuentaContableField;
            }
            set {
                if ((object.ReferenceEquals(this.CuentaContableField, value) != true)) {
                    this.CuentaContableField = value;
                    this.RaisePropertyChanged("CuentaContable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Porcentaje {
            get {
                return this.PorcentajeField;
            }
            set {
                if ((this.PorcentajeField.Equals(value) != true)) {
                    this.PorcentajeField = value;
                    this.RaisePropertyChanged("Porcentaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IngresosMap", Namespace="http://schemas.datacontract.org/2004/07/ModelMap")]
    [System.SerializableAttribute()]
    public partial class IngresosMap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presupuesto.PresupuestoSisWS.AnosMap AnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presupuesto.PresupuestoSisWS.CentroCostosMap CentroCostosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presupuesto.PresupuestoSisWS.CuentaContableMap CuentaContableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LinealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presupuesto.PresupuestoSisWS.MonedaMap MonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PuntualField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presupuesto.PresupuestoSisWS.AnosMap Ano {
            get {
                return this.AnoField;
            }
            set {
                if ((object.ReferenceEquals(this.AnoField, value) != true)) {
                    this.AnoField = value;
                    this.RaisePropertyChanged("Ano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presupuesto.PresupuestoSisWS.CentroCostosMap CentroCostos {
            get {
                return this.CentroCostosField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroCostosField, value) != true)) {
                    this.CentroCostosField = value;
                    this.RaisePropertyChanged("CentroCostos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presupuesto.PresupuestoSisWS.CuentaContableMap CuentaContable {
            get {
                return this.CuentaContableField;
            }
            set {
                if ((object.ReferenceEquals(this.CuentaContableField, value) != true)) {
                    this.CuentaContableField = value;
                    this.RaisePropertyChanged("CuentaContable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Lineal {
            get {
                return this.LinealField;
            }
            set {
                if ((this.LinealField.Equals(value) != true)) {
                    this.LinealField = value;
                    this.RaisePropertyChanged("Lineal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presupuesto.PresupuestoSisWS.MonedaMap Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Puntual {
            get {
                return this.PuntualField;
            }
            set {
                if ((this.PuntualField.Equals(value) != true)) {
                    this.PuntualField = value;
                    this.RaisePropertyChanged("Puntual");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnosMap", Namespace="http://schemas.datacontract.org/2004/07/ModelMap")]
    [System.SerializableAttribute()]
    public partial class AnosMap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AbrilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AgostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DiciembreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FebreroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal JulioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal JunioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MarzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MayoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NoviembreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OctubreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SeptiembreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Abril {
            get {
                return this.AbrilField;
            }
            set {
                if ((this.AbrilField.Equals(value) != true)) {
                    this.AbrilField = value;
                    this.RaisePropertyChanged("Abril");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Agosto {
            get {
                return this.AgostoField;
            }
            set {
                if ((this.AgostoField.Equals(value) != true)) {
                    this.AgostoField = value;
                    this.RaisePropertyChanged("Agosto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ano {
            get {
                return this.AnoField;
            }
            set {
                if ((this.AnoField.Equals(value) != true)) {
                    this.AnoField = value;
                    this.RaisePropertyChanged("Ano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Diciembre {
            get {
                return this.DiciembreField;
            }
            set {
                if ((this.DiciembreField.Equals(value) != true)) {
                    this.DiciembreField = value;
                    this.RaisePropertyChanged("Diciembre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Enero {
            get {
                return this.EneroField;
            }
            set {
                if ((this.EneroField.Equals(value) != true)) {
                    this.EneroField = value;
                    this.RaisePropertyChanged("Enero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Febrero {
            get {
                return this.FebreroField;
            }
            set {
                if ((this.FebreroField.Equals(value) != true)) {
                    this.FebreroField = value;
                    this.RaisePropertyChanged("Febrero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Julio {
            get {
                return this.JulioField;
            }
            set {
                if ((this.JulioField.Equals(value) != true)) {
                    this.JulioField = value;
                    this.RaisePropertyChanged("Julio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Junio {
            get {
                return this.JunioField;
            }
            set {
                if ((this.JunioField.Equals(value) != true)) {
                    this.JunioField = value;
                    this.RaisePropertyChanged("Junio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Marzo {
            get {
                return this.MarzoField;
            }
            set {
                if ((this.MarzoField.Equals(value) != true)) {
                    this.MarzoField = value;
                    this.RaisePropertyChanged("Marzo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Mayo {
            get {
                return this.MayoField;
            }
            set {
                if ((this.MayoField.Equals(value) != true)) {
                    this.MayoField = value;
                    this.RaisePropertyChanged("Mayo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Noviembre {
            get {
                return this.NoviembreField;
            }
            set {
                if ((this.NoviembreField.Equals(value) != true)) {
                    this.NoviembreField = value;
                    this.RaisePropertyChanged("Noviembre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Octubre {
            get {
                return this.OctubreField;
            }
            set {
                if ((this.OctubreField.Equals(value) != true)) {
                    this.OctubreField = value;
                    this.RaisePropertyChanged("Octubre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Septiembre {
            get {
                return this.SeptiembreField;
            }
            set {
                if ((this.SeptiembreField.Equals(value) != true)) {
                    this.SeptiembreField = value;
                    this.RaisePropertyChanged("Septiembre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PresupuestoSisWS.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        Presupuesto.PresupuestoSisWS.CompositeType GetDataUsingDataContract(Presupuesto.PresupuestoSisWS.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.CompositeType> GetDataUsingDataContractAsync(Presupuesto.PresupuestoSisWS.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCentrosCosto", ReplyAction="http://tempuri.org/IService1/getCentrosCostoResponse")]
        Presupuesto.PresupuestoSisWS.CentroCostosMap[] getCentrosCosto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCentrosCosto", ReplyAction="http://tempuri.org/IService1/getCentrosCostoResponse")]
        System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.CentroCostosMap[]> getCentrosCostoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateCentroCosto", ReplyAction="http://tempuri.org/IService1/updateCentroCostoResponse")]
        bool updateCentroCosto(int id, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateCentroCosto", ReplyAction="http://tempuri.org/IService1/updateCentroCostoResponse")]
        System.Threading.Tasks.Task<bool> updateCentroCostoAsync(int id, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProyectosCentrosCosto", ReplyAction="http://tempuri.org/IService1/getProyectosCentrosCostoResponse")]
        Presupuesto.PresupuestoSisWS.ProyectoCentroCostosMap[] getProyectosCentrosCosto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProyectosCentrosCosto", ReplyAction="http://tempuri.org/IService1/getProyectosCentrosCostoResponse")]
        System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.ProyectoCentroCostosMap[]> getProyectosCentrosCostoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProyectoPorCentroCosto", ReplyAction="http://tempuri.org/IService1/UpdateProyectoPorCentroCostoResponse")]
        bool UpdateProyectoPorCentroCosto(int id, bool estado, string codigoCentroCogosto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProyectoPorCentroCosto", ReplyAction="http://tempuri.org/IService1/UpdateProyectoPorCentroCostoResponse")]
        System.Threading.Tasks.Task<bool> UpdateProyectoPorCentroCostoAsync(int id, bool estado, string codigoCentroCogosto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateCuetaContable", ReplyAction="http://tempuri.org/IService1/updateCuetaContableResponse")]
        bool updateCuetaContable(int id, int tipoCC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateCuetaContable", ReplyAction="http://tempuri.org/IService1/updateCuetaContableResponse")]
        System.Threading.Tasks.Task<bool> updateCuetaContableAsync(int id, int tipoCC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getInflaciones", ReplyAction="http://tempuri.org/IService1/getInflacionesResponse")]
        Presupuesto.PresupuestoSisWS.InflacionMap[] getInflaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getInflaciones", ReplyAction="http://tempuri.org/IService1/getInflacionesResponse")]
        System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.InflacionMap[]> getInflacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateInflaciones", ReplyAction="http://tempuri.org/IService1/UpdateInflacionesResponse")]
        bool UpdateInflaciones(int id, string semestreI, string semestreII);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateInflaciones", ReplyAction="http://tempuri.org/IService1/UpdateInflacionesResponse")]
        System.Threading.Tasks.Task<bool> UpdateInflacionesAsync(int id, string semestreI, string semestreII);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddInflaciones", ReplyAction="http://tempuri.org/IService1/AddInflacionesResponse")]
        bool AddInflaciones(int anno, string semestreI, string semestreII);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddInflaciones", ReplyAction="http://tempuri.org/IService1/AddInflacionesResponse")]
        System.Threading.Tasks.Task<bool> AddInflacionesAsync(int anno, string semestreI, string semestreII);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMoneda", ReplyAction="http://tempuri.org/IService1/GetMonedaResponse")]
        Presupuesto.PresupuestoSisWS.MonedaMap[] GetMoneda();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMoneda", ReplyAction="http://tempuri.org/IService1/GetMonedaResponse")]
        System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.MonedaMap[]> GetMonedaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMoneda", ReplyAction="http://tempuri.org/IService1/AddMonedaResponse")]
        bool AddMoneda(string moneda, string descripcion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMoneda", ReplyAction="http://tempuri.org/IService1/AddMonedaResponse")]
        System.Threading.Tasks.Task<bool> AddMonedaAsync(string moneda, string descripcion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMonedaById", ReplyAction="http://tempuri.org/IService1/UpdateMonedaByIdResponse")]
        bool UpdateMonedaById(int id, string moneda, string descripcion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMonedaById", ReplyAction="http://tempuri.org/IService1/UpdateMonedaByIdResponse")]
        System.Threading.Tasks.Task<bool> UpdateMonedaByIdAsync(int id, string moneda, string descripcion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCuentaContable", ReplyAction="http://tempuri.org/IService1/getCuentaContableResponse")]
        Presupuesto.PresupuestoSisWS.CuentaContableMap[] getCuentaContable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCuentaContable", ReplyAction="http://tempuri.org/IService1/getCuentaContableResponse")]
        System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.CuentaContableMap[]> getCuentaContableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTipoCuentaContable", ReplyAction="http://tempuri.org/IService1/GetTipoCuentaContableResponse")]
        Presupuesto.PresupuestoSisWS.TipoCuentaContableMap[] GetTipoCuentaContable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTipoCuentaContable", ReplyAction="http://tempuri.org/IService1/GetTipoCuentaContableResponse")]
        System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.TipoCuentaContableMap[]> GetTipoCuentaContableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTipoCambio", ReplyAction="http://tempuri.org/IService1/GetAllTipoCambioResponse")]
        Presupuesto.PresupuestoSisWS.TipoCambioMap[] GetAllTipoCambio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTipoCambio", ReplyAction="http://tempuri.org/IService1/GetAllTipoCambioResponse")]
        System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.TipoCambioMap[]> GetAllTipoCambioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTipoCambio", ReplyAction="http://tempuri.org/IService1/AddTipoCambioResponse")]
        bool AddTipoCambio(int Id, int moneda, int ano, System.Collections.Generic.Dictionary<string, decimal> meses, string Tipo_Cambio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTipoCambio", ReplyAction="http://tempuri.org/IService1/AddTipoCambioResponse")]
        System.Threading.Tasks.Task<bool> AddTipoCambioAsync(int Id, int moneda, int ano, System.Collections.Generic.Dictionary<string, decimal> meses, string Tipo_Cambio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCargasSociales", ReplyAction="http://tempuri.org/IService1/GetAllCargasSocialesResponse")]
        Presupuesto.PresupuestoSisWS.CargasSocialesMap[] GetAllCargasSociales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCargasSociales", ReplyAction="http://tempuri.org/IService1/GetAllCargasSocialesResponse")]
        System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.CargasSocialesMap[]> GetAllCargasSocialesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllIngresos", ReplyAction="http://tempuri.org/IService1/GetAllIngresosResponse")]
        Presupuesto.PresupuestoSisWS.IngresosMap[] GetAllIngresos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllIngresos", ReplyAction="http://tempuri.org/IService1/GetAllIngresosResponse")]
        System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.IngresosMap[]> GetAllIngresosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Presupuesto.PresupuestoSisWS.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Presupuesto.PresupuestoSisWS.IService1>, Presupuesto.PresupuestoSisWS.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Presupuesto.PresupuestoSisWS.CompositeType GetDataUsingDataContract(Presupuesto.PresupuestoSisWS.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.CompositeType> GetDataUsingDataContractAsync(Presupuesto.PresupuestoSisWS.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public Presupuesto.PresupuestoSisWS.CentroCostosMap[] getCentrosCosto() {
            return base.Channel.getCentrosCosto();
        }
        
        public System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.CentroCostosMap[]> getCentrosCostoAsync() {
            return base.Channel.getCentrosCostoAsync();
        }
        
        public bool updateCentroCosto(int id, bool estado) {
            return base.Channel.updateCentroCosto(id, estado);
        }
        
        public System.Threading.Tasks.Task<bool> updateCentroCostoAsync(int id, bool estado) {
            return base.Channel.updateCentroCostoAsync(id, estado);
        }
        
        public Presupuesto.PresupuestoSisWS.ProyectoCentroCostosMap[] getProyectosCentrosCosto() {
            return base.Channel.getProyectosCentrosCosto();
        }
        
        public System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.ProyectoCentroCostosMap[]> getProyectosCentrosCostoAsync() {
            return base.Channel.getProyectosCentrosCostoAsync();
        }
        
        public bool UpdateProyectoPorCentroCosto(int id, bool estado, string codigoCentroCogosto) {
            return base.Channel.UpdateProyectoPorCentroCosto(id, estado, codigoCentroCogosto);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProyectoPorCentroCostoAsync(int id, bool estado, string codigoCentroCogosto) {
            return base.Channel.UpdateProyectoPorCentroCostoAsync(id, estado, codigoCentroCogosto);
        }
        
        public bool updateCuetaContable(int id, int tipoCC) {
            return base.Channel.updateCuetaContable(id, tipoCC);
        }
        
        public System.Threading.Tasks.Task<bool> updateCuetaContableAsync(int id, int tipoCC) {
            return base.Channel.updateCuetaContableAsync(id, tipoCC);
        }
        
        public Presupuesto.PresupuestoSisWS.InflacionMap[] getInflaciones() {
            return base.Channel.getInflaciones();
        }
        
        public System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.InflacionMap[]> getInflacionesAsync() {
            return base.Channel.getInflacionesAsync();
        }
        
        public bool UpdateInflaciones(int id, string semestreI, string semestreII) {
            return base.Channel.UpdateInflaciones(id, semestreI, semestreII);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateInflacionesAsync(int id, string semestreI, string semestreII) {
            return base.Channel.UpdateInflacionesAsync(id, semestreI, semestreII);
        }
        
        public bool AddInflaciones(int anno, string semestreI, string semestreII) {
            return base.Channel.AddInflaciones(anno, semestreI, semestreII);
        }
        
        public System.Threading.Tasks.Task<bool> AddInflacionesAsync(int anno, string semestreI, string semestreII) {
            return base.Channel.AddInflacionesAsync(anno, semestreI, semestreII);
        }
        
        public Presupuesto.PresupuestoSisWS.MonedaMap[] GetMoneda() {
            return base.Channel.GetMoneda();
        }
        
        public System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.MonedaMap[]> GetMonedaAsync() {
            return base.Channel.GetMonedaAsync();
        }
        
        public bool AddMoneda(string moneda, string descripcion, bool activo) {
            return base.Channel.AddMoneda(moneda, descripcion, activo);
        }
        
        public System.Threading.Tasks.Task<bool> AddMonedaAsync(string moneda, string descripcion, bool activo) {
            return base.Channel.AddMonedaAsync(moneda, descripcion, activo);
        }
        
        public bool UpdateMonedaById(int id, string moneda, string descripcion, bool activo) {
            return base.Channel.UpdateMonedaById(id, moneda, descripcion, activo);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateMonedaByIdAsync(int id, string moneda, string descripcion, bool activo) {
            return base.Channel.UpdateMonedaByIdAsync(id, moneda, descripcion, activo);
        }
        
        public Presupuesto.PresupuestoSisWS.CuentaContableMap[] getCuentaContable() {
            return base.Channel.getCuentaContable();
        }
        
        public System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.CuentaContableMap[]> getCuentaContableAsync() {
            return base.Channel.getCuentaContableAsync();
        }
        
        public Presupuesto.PresupuestoSisWS.TipoCuentaContableMap[] GetTipoCuentaContable() {
            return base.Channel.GetTipoCuentaContable();
        }
        
        public System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.TipoCuentaContableMap[]> GetTipoCuentaContableAsync() {
            return base.Channel.GetTipoCuentaContableAsync();
        }
        
        public Presupuesto.PresupuestoSisWS.TipoCambioMap[] GetAllTipoCambio() {
            return base.Channel.GetAllTipoCambio();
        }
        
        public System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.TipoCambioMap[]> GetAllTipoCambioAsync() {
            return base.Channel.GetAllTipoCambioAsync();
        }
        
        public bool AddTipoCambio(int Id, int moneda, int ano, System.Collections.Generic.Dictionary<string, decimal> meses, string Tipo_Cambio) {
            return base.Channel.AddTipoCambio(Id, moneda, ano, meses, Tipo_Cambio);
        }
        
        public System.Threading.Tasks.Task<bool> AddTipoCambioAsync(int Id, int moneda, int ano, System.Collections.Generic.Dictionary<string, decimal> meses, string Tipo_Cambio) {
            return base.Channel.AddTipoCambioAsync(Id, moneda, ano, meses, Tipo_Cambio);
        }
        
        public Presupuesto.PresupuestoSisWS.CargasSocialesMap[] GetAllCargasSociales() {
            return base.Channel.GetAllCargasSociales();
        }
        
        public System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.CargasSocialesMap[]> GetAllCargasSocialesAsync() {
            return base.Channel.GetAllCargasSocialesAsync();
        }
        
        public Presupuesto.PresupuestoSisWS.IngresosMap[] GetAllIngresos() {
            return base.Channel.GetAllIngresos();
        }
        
        public System.Threading.Tasks.Task<Presupuesto.PresupuestoSisWS.IngresosMap[]> GetAllIngresosAsync() {
            return base.Channel.GetAllIngresosAsync();
        }
    }
}
