//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA_CONTABLE
    {
        public string CUENTA_CONTABLE1 { get; set; }
        public string SECCION_CUENTA { get; set; }
        public string UNIDAD { get; set; }
        public string DESCRIPCION { get; set; }
        public string TIPO { get; set; }
        public string TIPO_DETALLADO { get; set; }
        public string TIPO_OAF { get; set; }
        public string SALDO_NORMAL { get; set; }
        public string CONVERSION { get; set; }
        public string TIPO_CAMBIO { get; set; }
        public string ACEPTA_DATOS { get; set; }
        public string CONSOLIDA { get; set; }
        public string USA_CENTRO_COSTO { get; set; }
        public string NOTAS { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime FECHA_HORA { get; set; }
        public string USUARIO_ULT_MOD { get; set; }
        public System.DateTime FCH_HORA_ULT_MOD { get; set; }
        public string ACEPTA_UNIDADES { get; set; }
        public string USO_RESTRINGIDO { get; set; }
        public string ORIGEN_CONVERSION { get; set; }
        public Nullable<byte> NoteExistsFlag { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.Guid> RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string REPORTE_PRESUPUESTO_GRUPO_1 { get; set; }
        public string REPORTE_PRESUPUESTO_GRUPO_2 { get; set; }
        public string REPORTE_PRESUPUESTO_GRUPO_3 { get; set; }
        public string VALIDA_PRESUP_CR { get; set; }
        public string U_AGRUPACION_1 { get; set; }
        public string U_AGRUPACION_2 { get; set; }
        public string U_AGRUPACION_3 { get; set; }
        public string CUENTA_IFRS { get; set; }
        public string USA_CONTA_ELECTRO { get; set; }
        public string VERSION { get; set; }
        public Nullable<System.DateTime> FECHA_INI_CE { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_CE { get; set; }
        public string COD_AGRUPADOR { get; set; }
        public string DESC_COD_AGRUP { get; set; }
        public string SUB_CTA_DE { get; set; }
        public string DESC_SUB_CTA { get; set; }
        public string NIVEL { get; set; }
    }
}
