//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PRESUPUESTOEntities : DbContext
    {
        public PRESUPUESTOEntities()
            : base("name=PRESUPUESTOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ANNO_MODULO> TBL_ANNO_MODULO { get; set; }
        public virtual DbSet<TBLANNO> TBLANNO { get; set; }
        public virtual DbSet<TBLCARGASSOCIALES> TBLCARGASSOCIALES { get; set; }
        public virtual DbSet<TBLCENTROCOSTO> TBLCENTROCOSTO { get; set; }
        public virtual DbSet<TBLCONFIGURACION> TBLCONFIGURACION { get; set; }
        public virtual DbSet<TBLCUENTACONTABLE> TBLCUENTACONTABLE { get; set; }
        public virtual DbSet<TBLEMPLEADO> TBLEMPLEADO { get; set; }
        public virtual DbSet<TBLINFLACION> TBLINFLACION { get; set; }
        public virtual DbSet<TBLITEM> TBLITEM { get; set; }
        public virtual DbSet<TBLMODULO> TBLMODULO { get; set; }
        public virtual DbSet<TBLMODULOITEM> TBLMODULOITEM { get; set; }
        public virtual DbSet<TBLMONEDA> TBLMONEDA { get; set; }
        public virtual DbSet<TBLPERFIL> TBLPERFIL { get; set; }
        public virtual DbSet<TBLPERMISO> TBLPERMISO { get; set; }
        public virtual DbSet<TBLPERMISOSUBITEM> TBLPERMISOSUBITEM { get; set; }
        public virtual DbSet<TBLPRESUPUESTO_PROYECCION_SALARIO> TBLPRESUPUESTO_PROYECCION_SALARIO { get; set; }
        public virtual DbSet<TBLPRESUPUESTOPROYECCIONINGRESO> TBLPRESUPUESTOPROYECCIONINGRESO { get; set; }
        public virtual DbSet<TBLPROYECCION_GASTO> TBLPROYECCION_GASTO { get; set; }
        public virtual DbSet<TBLPROYECTO> TBLPROYECTO { get; set; }
        public virtual DbSet<TBLTIPOGASTO> TBLTIPOGASTO { get; set; }
        public virtual DbSet<TBLTIPOINGRESO> TBLTIPOINGRESO { get; set; }
        public virtual DbSet<TBLTIPOLEGISLACION> TBLTIPOLEGISLACION { get; set; }
        public virtual DbSet<TBLTIPOPERMISO> TBLTIPOPERMISO { get; set; }
        public virtual DbSet<TBLTIPOPRESUPUESTO> TBLTIPOPRESUPUESTO { get; set; }
        public virtual DbSet<TBLTIPOPROYECCION> TBLTIPOPROYECCION { get; set; }
        public virtual DbSet<TBLUSUARIO> TBLUSUARIO { get; set; }
        public virtual DbSet<CENTRO_COSTO> CENTRO_COSTO { get; set; }
        public virtual DbSet<CUENTA_CONTABLE> CUENTA_CONTABLE { get; set; }
        public virtual DbSet<TBLCENTROCOSTO_bak> TBLCENTROCOSTO_bak { get; set; }
        public virtual DbSet<TBLcuentacontable_bak> TBLcuentacontable_bak { get; set; }
        public virtual DbSet<TBLTIPOCAMBIO> TBLTIPOCAMBIO { get; set; }
    
        public virtual int SP_ACTUALIZAR_CARGASOCIAL(Nullable<int> aNNO, string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var aNNOParameter = aNNO.HasValue ?
                new ObjectParameter("ANNO", aNNO) :
                new ObjectParameter("ANNO", typeof(int));
    
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZAR_CARGASOCIAL", aNNOParameter, mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_ACTUALIZAR_CENTRO_COSTO(string mODULO, string iTEM, string aNNO, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            var aNNOParameter = aNNO != null ?
                new ObjectParameter("ANNO", aNNO) :
                new ObjectParameter("ANNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZAR_CENTRO_COSTO", mODULOParameter, iTEMParameter, aNNOParameter, mENSAJE);
        }
    
        public virtual int SP_ACTUALIZAR_CIERRE_ANNO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZAR_CIERRE_ANNO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_ACTUALIZAR_CONFIGURACION(ObjectParameter mENSAJE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZAR_CONFIGURACION", mENSAJE);
        }
    
        public virtual int SP_ACTUALIZAR_ESTADO_CENTROCOSTO(string mODULO, string iTEM, string eSTADO, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZAR_ESTADO_CENTROCOSTO", mODULOParameter, iTEMParameter, eSTADOParameter, mENSAJE);
        }
    
        public virtual int SP_ACTUALIZAR_ESTADO_PROY_CENTRO_COSTO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZAR_ESTADO_PROY_CENTRO_COSTO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_ACTUALIZAR_INFLACION(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZAR_INFLACION", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_ACTUALIZAR_MONEDA(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZAR_MONEDA", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_ACTUALIZAR_PRE_PROY_INGRESO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZAR_PRE_PROY_INGRESO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_ACTUALIZAR_PROYECCION_GASTO(string mODULO, string iTEM, string aNNO, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            var aNNOParameter = aNNO != null ?
                new ObjectParameter("ANNO", aNNO) :
                new ObjectParameter("ANNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZAR_PROYECCION_GASTO", mODULOParameter, iTEMParameter, aNNOParameter, mENSAJE);
        }
    
        public virtual int SP_ACTUALIZAR_PROYECTOxCENTROCOSTO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZAR_PROYECTOxCENTROCOSTO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_ACTUALIZARPERMISOCENTROCOSTO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZARPERMISOCENTROCOSTO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_ACTUALZIAR_TIPOINGRESO_CUENTACONTABLE(string aNNO, ObjectParameter mENSAJE)
        {
            var aNNOParameter = aNNO != null ?
                new ObjectParameter("ANNO", aNNO) :
                new ObjectParameter("ANNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALZIAR_TIPOINGRESO_CUENTACONTABLE", aNNOParameter, mENSAJE);
        }
    
        public virtual int SP_ELIMINAR_PRE_PRO_SALARIO(string aNNO)
        {
            var aNNOParameter = aNNO != null ?
                new ObjectParameter("ANNO", aNNO) :
                new ObjectParameter("ANNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINAR_PRE_PRO_SALARIO", aNNOParameter);
        }
    
        public virtual int SP_ELIMINAR_PRE_PROY_INGRESO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINAR_PRE_PROY_INGRESO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_ELIMINAR_PRESUPUESTO_GASTO(string mODULO, string iTEM, string aNNO, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            var aNNOParameter = aNNO != null ?
                new ObjectParameter("ANNO", aNNO) :
                new ObjectParameter("ANNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINAR_PRESUPUESTO_GASTO", mODULOParameter, iTEMParameter, aNNOParameter, mENSAJE);
        }
    
        public virtual int SP_EVALUAR_PERMISOS(string mODULO, string iTEM, ObjectParameter mENSAJE, string pETICION, ObjectParameter rPTA)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            var pETICIONParameter = pETICION != null ?
                new ObjectParameter("PETICION", pETICION) :
                new ObjectParameter("PETICION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EVALUAR_PERMISOS", mODULOParameter, iTEMParameter, mENSAJE, pETICIONParameter, rPTA);
        }
    
        public virtual int SP_LOGIN_USUARIO(ObjectParameter mENSAJE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LOGIN_USUARIO", mENSAJE);
        }
    
        public virtual int SP_OBTENER_PERMISO_USUARIO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENER_PERMISO_USUARIO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_OBTENER_PERMISOCENTROCOSTO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENER_PERMISOCENTROCOSTO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_OBTENER_PRE_PROY_INGRESO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENER_PRE_PROY_INGRESO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_OBTENER_PRE_PROY_SALARIO(string aNNO, string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var aNNOParameter = aNNO != null ?
                new ObjectParameter("ANNO", aNNO) :
                new ObjectParameter("ANNO", typeof(string));
    
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENER_PRE_PROY_SALARIO", aNNOParameter, mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_OBTENER_PROYECCION_GASTO(string mODULO, string iTEM, string aNNO, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            var aNNOParameter = aNNO != null ?
                new ObjectParameter("ANNO", aNNO) :
                new ObjectParameter("ANNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENER_PROYECCION_GASTO", mODULOParameter, iTEMParameter, aNNOParameter, mENSAJE);
        }
    
        public virtual int SP_OBTENER_PROYECTOSINCENTROCOSTO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENER_PROYECTOSINCENTROCOSTO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_OBTENER_TIPO_CAMBIO(string mODULO, string iTEM, Nullable<int> aNNO, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            var aNNOParameter = aNNO.HasValue ?
                new ObjectParameter("ANNO", aNNO) :
                new ObjectParameter("ANNO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENER_TIPO_CAMBIO", mODULOParameter, iTEMParameter, aNNOParameter, mENSAJE);
        }
    
        public virtual int SP_OBTENERANNO(ObjectParameter mENSAJE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENERANNO", mENSAJE);
        }
    
        public virtual int SP_OBTENERCARGASSOCIALES(Nullable<int> aNNO, string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var aNNOParameter = aNNO.HasValue ?
                new ObjectParameter("ANNO", aNNO) :
                new ObjectParameter("ANNO", typeof(int));
    
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENERCARGASSOCIALES", aNNOParameter, mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_OBTENERCENTRODECOSTO(string aNNO, string mODULO, string iTEM, Nullable<int> iDTIPOPERMISO, ObjectParameter mENSAJE)
        {
            var aNNOParameter = aNNO != null ?
                new ObjectParameter("ANNO", aNNO) :
                new ObjectParameter("ANNO", typeof(string));
    
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            var iDTIPOPERMISOParameter = iDTIPOPERMISO.HasValue ?
                new ObjectParameter("IDTIPOPERMISO", iDTIPOPERMISO) :
                new ObjectParameter("IDTIPOPERMISO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENERCENTRODECOSTO", aNNOParameter, mODULOParameter, iTEMParameter, iDTIPOPERMISOParameter, mENSAJE);
        }
    
        public virtual int SP_OBTENERCUENTACONTABLE(ObjectParameter mENSAJE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENERCUENTACONTABLE", mENSAJE);
        }
    
        public virtual int SP_OBTENERCUENTACONTABLExTIPOGASTO(ObjectParameter mENSAJE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENERCUENTACONTABLExTIPOGASTO", mENSAJE);
        }
    
        public virtual int SP_OBTENERGASTOS_X_CENTROCOSTO(ObjectParameter mENSAJE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENERGASTOS_X_CENTROCOSTO", mENSAJE);
        }
    
        public virtual int SP_OBTENERINFLACION(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENERINFLACION", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_OBTENERMONEDA(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENERMONEDA", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_OBTENERPLANTILLAGASTO(ObjectParameter mENSAJE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENERPLANTILLAGASTO", mENSAJE);
        }
    
        public virtual int SP_OBTENERPLANTILLASALARIO(ObjectParameter mENSAJE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENERPLANTILLASALARIO", mENSAJE);
        }
    
        public virtual int SP_OBTENERPROYECTOXCENTRODECOSTO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENERPROYECTOXCENTRODECOSTO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_OBTENERTIPOGASTO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENERTIPOGASTO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_OBTENERTIPOINGREGOSCUENTACONTABLE(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENERTIPOINGREGOSCUENTACONTABLE", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_OBTENERTIPOINGRESO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENERTIPOINGRESO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_OBTENERTIPOINGRESOCENTROCOSTO(ObjectParameter mENSAJE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENERTIPOINGRESOCENTROCOSTO", mENSAJE);
        }
    
        public virtual ObjectResult<SP_OBTENERTIPOPROYECCION_Result> SP_OBTENERTIPOPROYECCION(ObjectParameter mENSAJE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OBTENERTIPOPROYECCION_Result>("SP_OBTENERTIPOPROYECCION", mENSAJE);
        }
    
        public virtual int SP_OBTERNERCENTROCOSTOxTIPOINGRESO(ObjectParameter mENSAJE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTERNERCENTROCOSTOxTIPOINGRESO", mENSAJE);
        }
    
        public virtual int SP_REGISTRAR_PERMISO_USUARIO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REGISTRAR_PERMISO_USUARIO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_REGISTRAR_PLANTILLA_GASTO(string mODULO, string iTEM, string aNNO, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            var aNNOParameter = aNNO != null ?
                new ObjectParameter("ANNO", aNNO) :
                new ObjectParameter("ANNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REGISTRAR_PLANTILLA_GASTO", mODULOParameter, iTEMParameter, aNNOParameter, mENSAJE);
        }
    
        public virtual int SP_REGISTRAR_PLANTILLA_SALARIO(string mODULO, string iTEM, string aNNO, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            var aNNOParameter = aNNO != null ?
                new ObjectParameter("ANNO", aNNO) :
                new ObjectParameter("ANNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REGISTRAR_PLANTILLA_SALARIO", mODULOParameter, iTEMParameter, aNNOParameter, mENSAJE);
        }
    
        public virtual int SP_REGISTRAR_PRE_PROY_SALARIO(string tIPOLEGISLACION, string aNNO, string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var tIPOLEGISLACIONParameter = tIPOLEGISLACION != null ?
                new ObjectParameter("TIPOLEGISLACION", tIPOLEGISLACION) :
                new ObjectParameter("TIPOLEGISLACION", typeof(string));
    
            var aNNOParameter = aNNO != null ?
                new ObjectParameter("ANNO", aNNO) :
                new ObjectParameter("ANNO", typeof(string));
    
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REGISTRAR_PRE_PROY_SALARIO", tIPOLEGISLACIONParameter, aNNOParameter, mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_REGISTRAR_PROYECTO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REGISTRAR_PROYECTO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_REGISTRAR_TIPO_CAMBIO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REGISTRAR_TIPO_CAMBIO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_REPORTE_COMPARATIVO_GASTO_X_CENTROCOSTO(string fECHAINICIAL, string fECHAFINAL, string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var fECHAINICIALParameter = fECHAINICIAL != null ?
                new ObjectParameter("FECHAINICIAL", fECHAINICIAL) :
                new ObjectParameter("FECHAINICIAL", typeof(string));
    
            var fECHAFINALParameter = fECHAFINAL != null ?
                new ObjectParameter("FECHAFINAL", fECHAFINAL) :
                new ObjectParameter("FECHAFINAL", typeof(string));
    
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REPORTE_COMPARATIVO_GASTO_X_CENTROCOSTO", fECHAINICIALParameter, fECHAFINALParameter, mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_REPORTE_COMPARATIVO_SALARIO_X_CENTROCOSTOS(string fECHAINICIAL, string fECHAFINAL, string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var fECHAINICIALParameter = fECHAINICIAL != null ?
                new ObjectParameter("FECHAINICIAL", fECHAINICIAL) :
                new ObjectParameter("FECHAINICIAL", typeof(string));
    
            var fECHAFINALParameter = fECHAFINAL != null ?
                new ObjectParameter("FECHAFINAL", fECHAFINAL) :
                new ObjectParameter("FECHAFINAL", typeof(string));
    
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REPORTE_COMPARATIVO_SALARIO_X_CENTROCOSTOS", fECHAINICIALParameter, fECHAFINALParameter, mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_REPORTE_EXACTUS(string fECHAINICIAL, string fECHAFINAL, string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var fECHAINICIALParameter = fECHAINICIAL != null ?
                new ObjectParameter("FECHAINICIAL", fECHAINICIAL) :
                new ObjectParameter("FECHAINICIAL", typeof(string));
    
            var fECHAFINALParameter = fECHAFINAL != null ?
                new ObjectParameter("FECHAFINAL", fECHAFINAL) :
                new ObjectParameter("FECHAFINAL", typeof(string));
    
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REPORTE_EXACTUS", fECHAINICIALParameter, fECHAFINALParameter, mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_REPORTE_GASTOS_X_CENTROCOSTO(string fECHAINICIAL, string fECHAFINAL, string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var fECHAINICIALParameter = fECHAINICIAL != null ?
                new ObjectParameter("FECHAINICIAL", fECHAINICIAL) :
                new ObjectParameter("FECHAINICIAL", typeof(string));
    
            var fECHAFINALParameter = fECHAFINAL != null ?
                new ObjectParameter("FECHAFINAL", fECHAFINAL) :
                new ObjectParameter("FECHAFINAL", typeof(string));
    
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REPORTE_GASTOS_X_CENTROCOSTO", fECHAINICIALParameter, fECHAFINALParameter, mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_REPORTE_GASTOS_X_PARTIDA(string fECHAINICIAL, string fECHAFINAL, string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var fECHAINICIALParameter = fECHAINICIAL != null ?
                new ObjectParameter("FECHAINICIAL", fECHAINICIAL) :
                new ObjectParameter("FECHAINICIAL", typeof(string));
    
            var fECHAFINALParameter = fECHAFINAL != null ?
                new ObjectParameter("FECHAFINAL", fECHAFINAL) :
                new ObjectParameter("FECHAFINAL", typeof(string));
    
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REPORTE_GASTOS_X_PARTIDA", fECHAINICIALParameter, fECHAFINALParameter, mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_REPORTE_SALARIOS_X_CENTROCOSTO(string fECHAINICIAL, string fECHAFINAL, string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var fECHAINICIALParameter = fECHAINICIAL != null ?
                new ObjectParameter("FECHAINICIAL", fECHAINICIAL) :
                new ObjectParameter("FECHAINICIAL", typeof(string));
    
            var fECHAFINALParameter = fECHAFINAL != null ?
                new ObjectParameter("FECHAFINAL", fECHAFINAL) :
                new ObjectParameter("FECHAFINAL", typeof(string));
    
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REPORTE_SALARIOS_X_CENTROCOSTO", fECHAINICIALParameter, fECHAFINALParameter, mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_REPORTEPRESUPUESTOGASTO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REPORTEPRESUPUESTOGASTO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_REPORTEPRESUPUESTOGASTO_MALO(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REPORTEPRESUPUESTOGASTO_MALO", mODULOParameter, iTEMParameter, mENSAJE);
        }
    
        public virtual int SP_SINCRONIZACION_EXACTUS(string mODULO, string iTEM, ObjectParameter mENSAJE)
        {
            var mODULOParameter = mODULO != null ?
                new ObjectParameter("MODULO", mODULO) :
                new ObjectParameter("MODULO", typeof(string));
    
            var iTEMParameter = iTEM != null ?
                new ObjectParameter("ITEM", iTEM) :
                new ObjectParameter("ITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SINCRONIZACION_EXACTUS", mODULOParameter, iTEMParameter, mENSAJE);
        }
    }
}
