//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEMPLEADO
    {
        public int LNGIDEMPLEADO { get; set; }
        public string STREMPLEADO { get; set; }
        public string STRACTIVO { get; set; }
        public string STRPUESTO { get; set; }
    }
}
