//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLINFLACION
    {
        public int LNGIDINFLACION { get; set; }
        public string STRAÑO { get; set; }
        public string STRSEMSTRE_1 { get; set; }
        public string STRSEMSTRE_2 { get; set; }
        public Nullable<System.DateTime> DTMFECHA { get; set; }
    }
}
