//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMODULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMODULO()
        {
            this.TBLMODULOITEM = new HashSet<TBLMODULOITEM>();
            this.TBLPERMISOSUBITEM = new HashSet<TBLPERMISOSUBITEM>();
        }
    
        public int LNGIDMODULO { get; set; }
        public string STRMODULO { get; set; }
        public string STRACTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMODULOITEM> TBLMODULOITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPERMISOSUBITEM> TBLPERMISOSUBITEM { get; set; }
    }
}
