//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMODULOITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMODULOITEM()
        {
            this.TBLPERMISO = new HashSet<TBLPERMISO>();
        }
    
        public int LNGIDMODULOITEM { get; set; }
        public Nullable<int> LNGIDMODULO { get; set; }
        public Nullable<int> LNGIDITEM { get; set; }
        public string STRACTIVO { get; set; }
    
        public virtual TBLMODULO TBLMODULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPERMISO> TBLPERMISO { get; set; }
    }
}
