//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPERMISOSUBITEM
    {
        public int LNGIDPERMISOSUBITEM { get; set; }
        public Nullable<int> LNGIDUSUARIO { get; set; }
        public Nullable<int> LNGIDMODULO { get; set; }
        public Nullable<int> LNGIDITEM { get; set; }
        public Nullable<int> LNGIDSUBITEM { get; set; }
        public string STREDITAR { get; set; }
        public string STRCONSULTAR { get; set; }
        public string STRADICIONAR { get; set; }
        public string STRELIMINAR { get; set; }
        public Nullable<int> INTIDTIPOPERMISO { get; set; }
        public string STRACTIVO { get; set; }
    
        public virtual TBLITEM TBLITEM { get; set; }
        public virtual TBLMODULO TBLMODULO { get; set; }
        public virtual TBLTIPOPERMISO TBLTIPOPERMISO { get; set; }
        public virtual TBLUSUARIO TBLUSUARIO { get; set; }
    }
}
