//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPERMISO
    {
        public int LNGIDPERMISO { get; set; }
        public Nullable<int> LNGIDMODULOITEM { get; set; }
        public Nullable<int> LNGIDUSUARIO { get; set; }
        public string STREDITAR { get; set; }
        public string STRCONSULTAR { get; set; }
        public string STRADICIONAR { get; set; }
        public string STRELIMINAR { get; set; }
    
        public virtual TBLMODULOITEM TBLMODULOITEM { get; set; }
        public virtual TBLUSUARIO TBLUSUARIO { get; set; }
    }
}
