//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTIPOPROYECCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLTIPOPROYECCION()
        {
            this.TBLPRESUPUESTOPROYECCIONINGRESO = new HashSet<TBLPRESUPUESTOPROYECCIONINGRESO>();
        }
    
        public int LNGIDTIPOPROYECCION { get; set; }
        public string STRTIPOPROYECCION { get; set; }
        public string STRACTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPRESUPUESTOPROYECCIONINGRESO> TBLPRESUPUESTOPROYECCIONINGRESO { get; set; }
    }
}
