//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargas_Sociales
    {
        public int Id { get; set; }
        public int Id_Cuenta_Contable { get; set; }
        public decimal Porcentaje { get; set; }
    
        public virtual Cuenta_Contable Cuenta_Contable { get; set; }
    }
}
