//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTRO_COSTO
    {
        public string CENTRO_COSTO1 { get; set; }
        public string DESCRIPCION { get; set; }
        public string ACEPTA_DATOS { get; set; }
        public string TIPO { get; set; }
        public Nullable<byte> NoteExistsFlag { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.Guid> RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string REPORTE_PRESUPUESTO { get; set; }
        public string U_AGRUPACION_1 { get; set; }
        public string U_AGRUPACION_2 { get; set; }
        public string U_AGRUPACION_3 { get; set; }
    }
}
