//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingresos
    {
        public int Id { get; set; }
        public int Id_Cuenta_Contable { get; set; }
        public int Id_Centro_Costos { get; set; }
        public int Id_Tipo_Moneda { get; set; }
        public int Id_Anos { get; set; }
        public bool Lineal { get; set; }
        public bool Puntual { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Monto { get; set; }
    
        public virtual Anos Anos { get; set; }
        public virtual Centro_Costos Centro_Costos { get; set; }
        public virtual Cuenta_Contable Cuenta_Contable { get; set; }
        public virtual Moneda Moneda { get; set; }
    }
}
