//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRESUPUESTOEntities : DbContext
    {
        public PRESUPUESTOEntities()
            : base("name=PRESUPUESTOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_ANNO_MODULO> TBL_ANNO_MODULO { get; set; }
        public virtual DbSet<TBLANNO> TBLANNO { get; set; }
        public virtual DbSet<TBLCARGASSOCIALES> TBLCARGASSOCIALES { get; set; }
        public virtual DbSet<TBLCENTROCOSTO> TBLCENTROCOSTO { get; set; }
        public virtual DbSet<TBLCONFIGURACION> TBLCONFIGURACION { get; set; }
        public virtual DbSet<TBLCUENTACONTABLE> TBLCUENTACONTABLE { get; set; }
        public virtual DbSet<TBLEMPLEADO> TBLEMPLEADO { get; set; }
        public virtual DbSet<TBLINFLACION> TBLINFLACION { get; set; }
        public virtual DbSet<TBLITEM> TBLITEM { get; set; }
        public virtual DbSet<TBLMODULO> TBLMODULO { get; set; }
        public virtual DbSet<TBLMODULOITEM> TBLMODULOITEM { get; set; }
        public virtual DbSet<TBLMONEDA> TBLMONEDA { get; set; }
        public virtual DbSet<TBLPERFIL> TBLPERFIL { get; set; }
        public virtual DbSet<TBLPERMISO> TBLPERMISO { get; set; }
        public virtual DbSet<TBLPERMISOSUBITEM> TBLPERMISOSUBITEM { get; set; }
        public virtual DbSet<TBLPRESUPUESTO_PROYECCION_SALARIO> TBLPRESUPUESTO_PROYECCION_SALARIO { get; set; }
        public virtual DbSet<TBLPRESUPUESTOPROYECCIONINGRESO> TBLPRESUPUESTOPROYECCIONINGRESO { get; set; }
        public virtual DbSet<TBLPROYECCION_GASTO> TBLPROYECCION_GASTO { get; set; }
        public virtual DbSet<TBLPROYECTO> TBLPROYECTO { get; set; }
        public virtual DbSet<TBLTIPOGASTO> TBLTIPOGASTO { get; set; }
        public virtual DbSet<TBLTIPOINGRESO> TBLTIPOINGRESO { get; set; }
        public virtual DbSet<TBLTIPOLEGISLACION> TBLTIPOLEGISLACION { get; set; }
        public virtual DbSet<TBLTIPOPERMISO> TBLTIPOPERMISO { get; set; }
        public virtual DbSet<TBLTIPOPRESUPUESTO> TBLTIPOPRESUPUESTO { get; set; }
        public virtual DbSet<TBLTIPOPROYECCION> TBLTIPOPROYECCION { get; set; }
        public virtual DbSet<TBLUSUARIO> TBLUSUARIO { get; set; }
        public virtual DbSet<CENTRO_COSTO> CENTRO_COSTO { get; set; }
        public virtual DbSet<CUENTA_CONTABLE> CUENTA_CONTABLE { get; set; }
        public virtual DbSet<TBLCENTROCOSTO_bak> TBLCENTROCOSTO_bak { get; set; }
        public virtual DbSet<TBLcuentacontable_bak> TBLcuentacontable_bak { get; set; }
        public virtual DbSet<TBLTIPOCAMBIO> TBLTIPOCAMBIO { get; set; }
    }
}
