//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto_Centro_Costos
    {
        public int Id_Proyecto { get; set; }
        public int Id_Centro_Costos { get; set; }
        public bool Activo { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Centro_Costos Centro_Costos { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
