//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ANNO_MODULO
    {
        public int LNGIDTRANSACCION { get; set; }
        public string STRTABLA { get; set; }
        public string STRANNO { get; set; }
        public string STRID { get; set; }
        public string STRACTIVO { get; set; }
        public Nullable<decimal> INTVALOR { get; set; }
    }
}
