//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCARGASSOCIALES
    {
        public int LNGIDCAGASOCIAL { get; set; }
        public string STRCUENTACONTABLE { get; set; }
        public string STRDESCRIPCIONCARGASOC { get; set; }
        public Nullable<System.DateTime> DTMFECHA { get; set; }
        public Nullable<decimal> FLTPORCENTAJE { get; set; }
    }
}
