//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPROYECTO
    {
        public int LNGIDPROYECTO { get; set; }
        public string STRCODIGO { get; set; }
        public string STRDESCRIPCION { get; set; }
        public string STRACTIVO { get; set; }
        public Nullable<System.DateTime> DTMFECHA { get; set; }
    }
}
