//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPRESUPUESTO_PROYECCION_SALARIO
    {
        public int LNGIDTRANSACCION { get; set; }
        public Nullable<int> LNGIDUSUARIO { get; set; }
        public Nullable<int> LNGIDCENTROCOSTO { get; set; }
        public Nullable<int> LNGIDMONEDA { get; set; }
        public Nullable<int> LNGIDCUENTACONTABLE { get; set; }
        public Nullable<int> LNGIDTIPOPRESUPUESTO { get; set; }
        public Nullable<int> LNGIDFUNCIONARIO { get; set; }
        public string STRPUESTO { get; set; }
        public Nullable<double> FLTENERO { get; set; }
        public Nullable<double> FLTFEBRERO { get; set; }
        public Nullable<double> FLTMARZO { get; set; }
        public Nullable<double> FLTABRIL { get; set; }
        public Nullable<double> FLTMAYO { get; set; }
        public Nullable<double> FLTJUNIO { get; set; }
        public Nullable<double> FLTJULIO { get; set; }
        public Nullable<double> FLTAGOSTO { get; set; }
        public Nullable<double> FLTSEPTIEMBRE { get; set; }
        public Nullable<double> FLTOCTUBRE { get; set; }
        public Nullable<double> FLTNOVIEMBRE { get; set; }
        public Nullable<double> FLTDICIEMBRE { get; set; }
        public Nullable<int> LNGIDTIPOLEGISLACION { get; set; }
        public string STRSEMSTRE_1 { get; set; }
        public string STRSEMSTRE_2 { get; set; }
        public Nullable<System.DateTime> DTRFECHA { get; set; }
        public Nullable<int> LNGIDCARGASOCIAL { get; set; }
        public string STRMONTO_COLONES { get; set; }
        public string STRMONTO_DOLARES { get; set; }
        public string STRESTADOPORC1 { get; set; }
        public string STRESTADOPORC2 { get; set; }
        public string STRANNO { get; set; }
    
        public virtual TBLCENTROCOSTO TBLCENTROCOSTO { get; set; }
        public virtual TBLCUENTACONTABLE TBLCUENTACONTABLE { get; set; }
        public virtual TBLMONEDA TBLMONEDA { get; set; }
        public virtual TBLUSUARIO TBLUSUARIO { get; set; }
        public virtual TBLTIPOPRESUPUESTO TBLTIPOPRESUPUESTO { get; set; }
        public virtual TBLTIPOLEGISLACION TBLTIPOLEGISLACION { get; set; }
    }
}
