//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUSUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUSUARIO()
        {
            this.TBLPERMISO = new HashSet<TBLPERMISO>();
            this.TBLPERMISOSUBITEM = new HashSet<TBLPERMISOSUBITEM>();
            this.TBLPRESUPUESTO_PROYECCION_SALARIO = new HashSet<TBLPRESUPUESTO_PROYECCION_SALARIO>();
            this.TBLPRESUPUESTOPROYECCIONINGRESO = new HashSet<TBLPRESUPUESTOPROYECCIONINGRESO>();
        }
    
        public int LNGIDUSUARIO { get; set; }
        public Nullable<int> LNGIDPERFIL { get; set; }
        public string STRUSUARIO { get; set; }
        public string STRNOMBRE { get; set; }
        public string STRDOMINIO { get; set; }
        public string STRACTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPERMISO> TBLPERMISO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPERMISOSUBITEM> TBLPERMISOSUBITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPRESUPUESTO_PROYECCION_SALARIO> TBLPRESUPUESTO_PROYECCION_SALARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPRESUPUESTOPROYECCIONINGRESO> TBLPRESUPUESTOPROYECCIONINGRESO { get; set; }
    }
}
