//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Cambio
    {
        public int Id { get; set; }
        public int Ano { get; set; }
        public int Id_Moneda { get; set; }
        public string Mes { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> Id_Tipo_Tipo_Cambio { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Tipo_Tipo_Cambio Tipo_Tipo_Cambio { get; set; }
    }
}
